name: "CI"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - name: "Initializes terraform"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform -chdir=github init -input=false
          terraform -chdir=heroku init -input=false

      - name: "Run terraform to check for formatting"
        run: terraform fmt -check

      - name: "Run validation to check for issues"
        run: |
          terraform -chdir=github validate -json
          terraform -chdir=heroku validate -json

  build:
    needs:
      - test
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - name: "Initializes terraform"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform -chdir=github init -input=false
          terraform -chdir=heroku init -input=false

      - name: "Generate terraform plan"
        run: |
          terraform -chdir=github plan -input=false
          terraform -chdir=heroku plan -input=false
