name: "CI"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - name: "Run terraform to check for formatting"
        run: terraform fmt -check

  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v1

      - name: "Run terraform to check for formatting"
        run: terraform -chdir=github init
